spring:
  h2.console:
    enabled: true
    path: '/console'
  main:
    banner-mode: off
  datasource:
    url: 'jdbc:h2:file:Y:/Project/todo-app/todo-db'
task.template.allowMultipleTasks: false


#spring.jpa.properties.hibernate.hbm2ddl.auto=create